//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IdInventario { get; set; }
        public int IdBodega { get; set; }
        public int IdProducto { get; set; }
        public int Existencia { get; set; }
        public int Disponible { get; set; }
        public int Daniado { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int PrecioVenta { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
