//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDetalleBoleta
    {
        public int IdBoleta { get; set; }
        public int IdMovimiento { get; set; }
        public string Producto { get; set; }
        public int Cantidad { get; set; }
        public int Dañado { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha_de_Vencimiento { get; set; }
    }
}
