//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEncabezadoFactura
    {
        public string Sucursal { get; set; }
        public string Cliente { get; set; }
        public string Nit { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string ApellidoPrim { get; set; }
    }
}
