//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEntradaSalida
    {
        public int IdBoleta { get; set; }
        public int IdBodega { get; set; }
        public System.DateTime FechaBoleta { get; set; }
        public string TipoBoleta { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal PrecioRef { get; set; }
    }
}
