//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFacturaDetalle
    {
        public int IdFactura { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public string Nit { get; set; }
        public string Nombre { get; set; }
        public string NombreSeg { get; set; }
        public string ApellidoPrim { get; set; }
        public string ApellidoSeg { get; set; }
        public string Articulo { get; set; }
        public string DireccionCliente { get; set; }
        public string DireccionSucursal { get; set; }
        public string Sucursal { get; set; }
        public string Municipio { get; set; }
        public string Departamento { get; set; }
        public string DepartamentoCliente { get; set; }
        public string MunicipioCliente { get; set; }
    }
}
