//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EleganciaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMunicipio
    {
        public string Municipio { get; set; }
        public int IdDepartamento { get; set; }
        public int Expr1 { get; set; }
        public int IdMunicipio { get; set; }
        public string Departamento { get; set; }
    }
}
